import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import { MdKeyboardArrowLeft, MdArrowForward, MdMaximize } from "react-icons/md";

export default function secondSplash() {
    return (
        <div className={styles.container}>
      <Head>
        <title>Mobile Splash Screen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.topbar}>
            <div className={styles.backto}>
                <a href='../'>
                    < MdKeyboardArrowLeft size={20} style={{ fill: '#6686D8', padding: '1px 0' }} />
                </a>
          </div>
          <div className={styles.skip}>
            <a href="#">Skip</a>
          </div>
        </div>
        <img src='/Illustration2.png' />

        <div className={styles.card}>
          <div className={styles.description}>
          <h3>Always use a mask</h3>
          <p>always use a mask when you want to travel and keep your  body immunity</p>
          </div>
          <div className={styles.bottombar}>
            <div className={styles.steps}>
              <MdMaximize size={20} style={{ fill: '#CBD6F3', padding: '1px 0' }} />
              <MdMaximize size={20} style={{ fill: '#6686D8', padding: '1px 0' }} />
              <MdMaximize size={20} style={{ fill: '#CBD6F3', padding: '1px 0' }} />
            </div>
            <div className={styles.nextto}>
              <a href="./third-splash">
                <MdArrowForward size={27} style={{ fill: '#ddd' }} />
              </a>
          </div>
          </div>
        </div>
        
      </main>

        </div>
        
    )
}