import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import { MdKeyboardArrowLeft, MdArrowForward, MdMaximize } from "react-icons/md";

export default function thirdSplash() {
    return (
        <div className={styles.container}>
      <Head>
        <title>Mobile Splash Screen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.topbar}>
            <div className={styles.backto}>
                <a href='./second-splash'>
                    < MdKeyboardArrowLeft size={20} style={{ fill: '#6686D8', padding: '1px 0' }} />
                </a>
          </div>
        </div>
        <img src='/Illustration3.png' />

        <div className={styles.card}>
          <div className={styles.description}>
          <h3>Work from home</h3>
          <p>To avoid the spread of covid 19. You can do office work from home and always be close to your family</p>
          </div>
          <div className={styles.bottombar}>
            <div className={styles.steps}>
              <MdMaximize size={20} style={{ fill: '#CBD6F3', padding: '1px 0' }} />
              <MdMaximize size={20} style={{ fill: '#CBD6F3', padding: '1px 0' }} />
              <MdMaximize size={20} style={{ fill: '#6686D8', padding: '1px 0' }} />
            </div>
            <div className={styles.nextto}>
              <a href="#">
                <MdArrowForward size={27} style={{ fill: '#ddd' }} />
              </a>
          </div>
          </div>
        </div>
        
      </main>

        </div>
        
    )
}